### ISSUE TITLE
Issue with heroku part of Blog tutorial

### ISSUE THREAD

**Issue by flips** [padrino/padrino-docs#105]
I just completed the blog tutorial. I had a couple of issue, like those mentioned in the comment below the tutorial itself. But I also had one issue with the heroku part.
`heroku run rake ar:migrate` would not run (pg didn't seem to be installed).

`Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).`

I installed postgres-dev package locally and ran a `bundle --with production`, and then checked in that updated `Gemfile.lock`. (I did not switch :development away from sqlite3.)
Then heroku seemed to get postgresql installed and everything ran as planned.

**Comment by adam12** [comment]
Thank you for your report! :+1:

**Comment by wikimatze** [comment]
Thank you very much.
