### ISSUE TITLE
How to localize your app suggests Padrino.before_load but app locales are not loaded yet

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-docs#109]
The docs [recommends one use `Padrino.before_load`](http://padrinorb.com/guides/features/localization/#how-to-localize-your-app) but when this runs `app/locale` has not been loaded, so assigning a locale that's not part of Padrino will result in a failure even though the locale is configured in `app/locale`.

The right way to go about the seems to be ~~via the app's `configure` hook~~ just adding the local locales to `I18n.load_path` yourself in `before_load` or `configure`.

**Comment by adam12** [comment]
I was just looking at this,

The load path for the locales is setup in the `setup_locale` method, called during `setup_application!`.

Unfortunately, It's called much later than both `before_load` and `after_load`, so I can't see either of those hooks working.

Calling `I18n.load_path` manually works, but you lose some of the *special sauce* provided by the Padrino reloader.

**Comment by sshaw** [comment]
It's also worth noting that setting `I18n.locale` to `:de` in `before_load` *will not* actually set the request's locale to `:de`. I18n uses thread local storage and in most (all?) cases the `before_load` thread  is different than the Rack handler's.

**Comment by sshaw** [comment]
Fixed by #127.

**Comment by wikimatze** [comment]
Thanks @sshaw for fixing the issues with the locales.
