### ISSUE TITLE
Blog Tutorial Improvements

### ISSUE THREAD

**Issue by adam12** [padrino/padrino-docs#119]
I ran through the blog tutorial to verify accuracy, and I made a few observations that could translate into improvements.

## Remove: Section on updating database configuration manually from Heroku DATABASE_URL variable

As this step technically isn't needed to complete the tutorial, I can't help but wonder if it should just be removed. As the values won't match up to what the user would be seeing, I wonder if it might be a source of confusion to newcomers.

## Remove: Addition to dependency_paths

Looks like `default_dependency_paths` already includes this path, allowing us to remove this step.

## Consistency: Settle on `bundle exec rake` or `padrino rake`

I've never seen `padrino rake` until following the tutorial. Maybe someone else can advise whether one or the other is better suited.

## Remove: Tweak to `db/seeds.rb`

I was prompted for a username and password when seeding. I think this can be safely removed.

<hr>

I'm willing to take care of these items, barring no objections from the core team.

**Comment by nesquena** [comment]
All of these changes look correct to me and would be welcome updates. cc @wikimatze @ujifgc for any additional feedback

**Comment by wikimatze** [comment]
Feel free to update the article, we will review it.
