### ISSUE TITLE
Docs on caching are out of date

### ISSUE THREAD

**Issue by spikeheap** [padrino/padrino-docs#124]
#### Do you want to request a *feature* or report a *bug*?

This is a documentation bug.

#### What is the current behavior?

Visiting the [Padrino caching documentation](http://padrinorb.com/guides/features/padrino-cache/) I am told to specify the cache as follows:

```
Padrino.cache = Padrino::Cache::Store::Memory.new(50)
```

Following those instructions yields the following error:

```
NameError: uninitialized constant Padrino::Cache::Store
```

The above applies to the creation of all different types of store.

#### What is the expected behavior?

The documentation should tell me to create a cache following the new approach:

```
Padrino.cache = Padrino::Cache.new(:LRUHash)
```

The documentation in the [padrino-cache module](https://github.com/padrino/padrino-framework/tree/master/padrino-cache) worked for me.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

- Ruby 2.3.1
- Padrino 0.13.3.2

I've not tested it for other versions, as this is a new development for us.

**Comment by adam12** [comment]
The old and new approach are identical. Clerical error?

**Comment by spikeheap** [comment]
Indeed @adam12, it's been one of those days :). Updated the 'correct' version of the initialisation command to match https://github.com/padrino/padrino-framework/tree/master/padrino-cache.

**Comment by wikimatze** [comment]
Hi @spikeheap thanks for your report and thanks for correcting this error report. Do you mind updating the documentation on your own?

**Comment by spikeheap** [comment]
I've actually just been looking at that – earlier I wanted to raise this issue in case I didn't get round to it.

I'm happy to update the documentation. The readme in https://github.com/padrino/padrino-framework/tree/master/padrino-cache seems similar to this repo's contents (but updated to work), so would it be reasonable for me to just port over that entire file (tweaking the frontmatter of course)?
