### ISSUE TITLE
Publish Updated Docs

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-docs#129]
There have be [a lot of commits](https://github.com/padrino/padrino-docs/compare/b2f5ca1ea32648780e943f8a3c0a2b08ff823696...2ee665aa8055f8b8b5913a342043e48304e536ab) some containing corrections to the live docs.

**Comment by nesquena** [comment]
@wikimatze can you push out latest doc updates?

**Comment by wikimatze** [comment]
Done via https://github.com/padrino/padrino-web/commit/d80968db37ebbba13bf9ac2e3aff5ddb0718d089
