### ISSUE TITLE
Notes about standalone-usage-in-sinatra.md guide

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-docs#53]
It says, that the padrino-cache gem is not implemented so far? Is this true? I dunno right now.

**Comment by nesquena** [comment]
It is implemented now, it works pretty well. Guide http://padrinorb.com/guides/padrino-cache/ is almost right but a bit out of date. I think I fixed it up a bit in the textile version

**Comment by wikimatze** [comment]
Okay.

**Comment by wikimatze** [comment]
I'll check it!
