### ISSUE TITLE
Guide length and organization

### ISSUE THREAD

**Issue by angeloashmore** [padrino/padrino-docs#69]
On discussing difficulty in navigation guide pages (from https://github.com/padrino/padrino-web-new/issues/18):

> Rather than discussing issues with the proposed solution, let's discuss problems with the current implementation.

> 1. **Guides are very long with many sections.**
2. Content width is somewhat narrow, especially for the font size.
3. **Guides are listed all together rather than by type or logical progression.**

> These are fairly easy problems to solve:

> 1. **Separate guides into smaller sub-guides. Content would be the same, but broken into multiple pages. See [Lotus's docs][0] for an example.**
2. Increase overall maximum page width. Since the CSS is set using Susy and percentages, everything should scale nicely automatically.
3. **Add sub-headers to the guides and break them into logical categories. Again, see [Lotus's docs][0] for an example.**

> These structural solutions should, in theory, make a TOC unnecessary. I feel this is a better solution, but I'd like to hear others' opinions.

The docs were separated from the website in this repository to allow us to maintain documentation without caring about the website's implementation. Thus, we should make these organizational changes here first.

As a side effect, this should allow the docs to remove files like [_sidebar.slim][1] as it is website logic.

[0]: http://lotusrb.org/guides/getting-started/
[1]: https://github.com/padrino/padrino-docs/blob/master/guides/_sidebar.slim

**Comment by angeloashmore** [comment]
I'm starting to explore what such a structure would look like here: [angeloashmore/padrino-docs][0]

[0]: https://github.com/angeloashmore/padrino-docs

**Comment by wikimatze** [comment]
Will soon take the time to explore your ideas.

**Comment by angeloashmore** [comment]
## Changes
- Wider page
- Guides separated into chapters
- Sidebar styling adjusted (removed dividing lines and smaller spacing)

![screen shot 2016-01-10 at 12 53 57 pm](https://cloud.githubusercontent.com/assets/8601064/12224594/576026da-b799-11e5-9771-e7ee7c04dfd4.png)

**Comment by angeloashmore** [comment]
@padrino/core-members Thoughts on guide restructuring?
