### ISSUE TITLE
Generator guide is missing `migration-format`

### ISSUE THREAD

**Issue by choix** [padrino/padrino-docs#70]
I figure out that project generator configuration option list is missing `--migration-format=timestamp` option. I wanted to create a pull request but I don't know neither `Default` value nor `Aliases` for migration format.

**Comment by wikimatze** [comment]
Hi @choix don't know exactly where your problem is. Can you outline the change in the docs? Do you have problems finding the place where to change the docs?

**Comment by wikimatze** [comment]
Thanks for the advice.
