### ISSUE TITLE
FAQ page is gone

### ISSUE THREAD

**Issue by mariozig** [padrino/padrino-docs#83]
While fixing some broken links in [padrino/pardino-framework](https://github.com/padrino/padrino-framework/)'s README I came across a broken link to an old FAQ page. 

Looking through this repo it appears the FAQ page was removed and I can't tell if that was on purpose or not... If it was please close this issue.  If not, then we should investigate building out an extensive list of questions/answers.

For now I've removed the FAQ reference from [padrino/pardino-framework](https://github.com/padrino/padrino-framework/)'s README.  PR here:  [Fixing all the broken links](https://github.com/padrino/padrino-framework/pull/2015)

**Comment by wikimatze** [comment]
I've migrated it under <http://padrinorb.wikimatze.de/faq/> but I doubt that we will maintain it. What's the opinion of other @padrino/collaborators.

**Comment by nesquena** [comment]
Oh yeah forgot about that page. Probably not really necessary to bring it back at this point, we should just remove the link.
